export const ADD_CARD = 'ADD_CARD'
export const ADD_LIST = 'ADD_LIST'
export const DRAG_HAPPENED = 'DRAG_HAPPENED'
export const EDIT_CARD = 'EDIT_CARD'
export const DELETE_CARD = 'DELETE_CARD'
export const EDIT_LIST_TITLE = 'EDIT_LIST_TITLE'
